### ISSUE TITLE
How about 'brew'ing some snake oil?

### ISSUE THREAD

**Issue by MadBomber** [Squarespace/pgbedrock#11]
On my Mac ...
$ pip install --upgrade pip
Collecting pip
....
Successfully installed pip-9.0.3

$ pip install wheel
Requirement already satisfied: wheel in /usr/local/lib/python2.7/site-packages

$ which wheel
/usr/local/bin/wheel

$ wheel version
wheel 0.30.0

$ wheel install pgbedrock
No match for requirement pgbedrock

$ which pgbedrock
$

No Joy in MuddVille ...

**Comment by MadBomber** [comment]
Never mind ....  Your doc was the first time I've seen the phrase "wheels install" and I got confused.

$ pip install pgbedrock

please close the issue.

**Comment by zcmarine** [comment]
Ok, glad you figured it out! If there's something you think should be changed in the README please let me know and/or put in a PR!
